config/routes.rb
Rails.application.routes.draw do
  get 'statics/coming'
  devise_for :users
  resources :users, only: :index
  resources :products
  resources :bids, only: [:index, :create]
  get "bids/render_bids_row"

  # root "statics#coming"
  root "bids#index"
end

app/models/bid.rb
class Bid < ApplicationRecord
  belongs_to :user
  belongs_to :product

  validates :amount, presence: true

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      col_names = ["ID", "Producto", "Oferta", "Usuario", "Creado", "Actualizado"]
      csv << col_names
      all.each do |bid|
        created_at = bid.attributes["created_at"]
        updated_at = bid.attributes["updated_at"]
        user_id = bid.attributes["user_id"]
        attributes =
          bid
            .attributes
            .merge("ID" => bid.id,
                   "Producto" => bid.product.name,
                   "Creado" => created_at.strftime("%d/%m/%Y - %H:%M"),
                   "Actualizado" => updated_at.strftime("%d/%m/%Y - %H:%M"),
                   "Usuario" => User.find(user_id).full_name,
                   "Oferta" => "$#{bid.amount}")
        csv << attributes.values_at(*col_names)
      end
    end
  end
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def index
    @products = Product.all.shuffle
    search_products_where_user_is_winning
  end

  def create
    amount = (params[:bids][:amount].presence || params[:placeholder_amount]).to_d

    message = "No se puede crear una oferta para un producto vacío."
    return_with_error_message(message) and return if params[:product_id].blank?
    product = Product.find(params[:product_id])

    message = "Tu oferta es menor a la oferta actual."
    return_with_error_message(message) and return if amount <= product.max_bid_amount.to_d

    product_ids = params[:product_ids_order].to_s.split(" ")
    if product_ids.present?
      @products = Product.find(product_ids)
    else
      @products = Product.all
    end

    @bid = product.bids.new(amount: amount, user_id: current_user.id)

    if @bid.save
      search_products_where_user_is_winning
      @message = "Tu oferta se ha enviado"
      respond_to do |format|
        format.html do
          flash[:notice] = @message
          redirect_to bids_path
        end
        format.js
      end
    else
      search_products_where_user_is_winning
      respond_to do |format|
        @error_message = @bid.errors.full_messages.join(",")
        format.html do
          flash[:alert] = error_message
          redirect_to bids_path
        end
        format.js
      end
    end
  end

  def return_with_error_message(message)
    @error_message = message
    respond_to do |format|
      format.html do
        flash[:alert] = @error_message
        redirect_to bids_path
      end
      format.js
    end
  end

  def render_bids_row
    product_ids = params[:product_ids_order].to_s.split(" ")
    if product_ids.present?
      @products = Product.find(product_ids)
    else
      @products = Product.all
    end

    search_products_where_user_is_winning

    render layout: false
  end

  def search_products_where_user_is_winning
    return unless current_user.present?

    bids_whit_max_amount_ids = Product.all.map do |product|
      max_bid_amount = product.max_bid_amount
      if max_bid_amount && product.bids.present?
        [product.bids.where(amount: product.max_bid_amount).pluck(:id)]
      end
    end
    bids_whit_max_amount = Bid.where(id: bids_whit_max_amount_ids.flatten, user_id: current_user.id)
    @products_user_winning = bids_whit_max_amount.map{|bid| bid.product}
  end
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/views/bids/_bids_products.html.erb
<% @products.each do |product| %>
  <div class="p-3">
    <div class="card mb-3 p-3 h-100 <%= 'border border-success alert-success' if current_user.present? && @products_user_winning&.include?(product) %>">
      <div class="row no-gutters">
        <div class="col-12 text-center">
          <h5 class="card-title">
            <%= product.name %>
            <%= "<span style='font-size:40px;' class='pl-2'>&#127881;</span>".html_safe if current_user.present? && @products_user_winning&.include?(product) %>
          </h5>
        </div>
        <div class="col-md-4">
          <a href="#" data-toggle="modal" data-target="#modal_product_<%= product.id %>">
            <%= image_tag(product.image_url, class: "img-thumbnail") %>
          </a>
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <p class="card-text"><%= product.description.truncate(100) %></p>
          </div>
          <div class="col">
            <div class="font-weight-bold text-center alert <%= current_user.present? && @products_user_winning&.include?(product) ? 'alert-success border border-success' : 'alert-primary' %>" role="alert">
              Oferta actual: <%= number_to_currency product.max_bid_amount %>
            </div>
            <div><%= "<p class='text-success'>Enhorabuena, vas ganando este producto.</p>".html_safe if current_user.present? && @products_user_winning&.include?(product) %></div>
          </div>
        </div>
      </div>
      <% if current_user %>
        <div class="col my-1 d-flex align-items-end">
          <%= form_tag(Bid.new, class: "form_bid form-inline mx-auto", remote: true) do %>
            <span class="span_product_name d-none"><%= product.name %></span>
            <span class="div_bid_hidden_fields">
              <%= hidden_field_tag :product_id, product.id %>
              <%= hidden_field_tag :product_ids_order, @products.map(&:id) %>
              <%= hidden_field_tag :placeholder_amount, product.next_bid_amount %>
            </span>

            <div class="div_bid_amount_field">
              <div class="input-group">
                <div class="input-group-prepend">
                  <span class="input-group-text" id="validatedInputGroupPrepend">$</span>
                </div>
                <%= number_field_tag "bids[amount]", "", class: "form-control mr-2 bid_amount_product_#{product.id}", placeholder: product.next_bid_amount %>
              </div>
              <div class="invalid-feedback bid_error_message_product_<%= product.id %>">
                Algo salió mal, por favor vuelva a intentar más tarde.
              </div>
            </div>

            <%= submit_tag "Ofertar", class: "btn btn-primary" %>
          <% end %>
        </div>
      <% else %>
        <div class="col">
          <div class="mt-3">
            <%= link_to "Inicia Sessión", new_user_session_path, class: "col m-1 btn btn-primary" %>
            <div class="col text-center">
              <%= link_to "ó Regístrate para poder ofertar", new_registration_path(:user) %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

<script type="text/javascript">
  $(".form_bid").on("submit", function(event){
    event.preventDefault();
    var form = $(this);
    var hidden_fields = form.find(".div_bid_hidden_fields").clone();
    var amount_field  = form.find(".div_bid_amount_field").clone();
    var product_name  = form.find(".span_product_name").clone().removeClass("d-none");

    var general_form = $("#general_form_bid");
    general_form.find(".div_bid_hidden_fields").html(hidden_fields);
    general_form.find(".div_bid_amount_field").html(amount_field);
    general_form.find(".span_product_name").html(product_name);
    $("#modal_place_bid").modal("show");
    return false;
  });
</script>

app/views/bids/create.js.erb
$("#bids_products_row").html('<%= j render "bids/bids_products" %>');

<% if @error_message.present? %>
  $(".bid_amount_product_<%= @bid.product_id %>").addClass("is-invalid");
  $(".bid_amount_product_<%= @bid.product_id %>").closest(".input-group").addClass("is-invalid");
  $(".bid_error_message_product_<%= @bid.product_id %>").html("<%= @error_message %>");
<% else %>
  $("#modal_place_bid").modal("hide");
<% end %>

app/views/bids/index.html.erb
<div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 my-4" id="bids_products_row">
  <%= render "bids/bids_products" %>
</div>

<% @products.each do |product| %>
  <div class="modal fade" id="modal_product_<%= product.id %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-xl">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel"><%= product.name %></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="row">
            <div class="col d-flex justify-content-center">
              <div class="card mb-3 col-12 border-0">
                <div class="row no-gutters p-4">
                  <div class="col-md-7 d-flex align-items-center">
                    <%= image_tag(product.image_url, class: "img-thumbnail") %>
                  </div>
                  <div class="col-md-5">
                    <div class="card-body">
                      <p class="card-text"><%= product.description %></p>
                    </div>
                    <div class="col">
                      <div class="alert alert-primary font-weight-bold text-center" role="alert">
                        Oferta actual: <%= number_to_currency(product.max_bid_amount) %>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
<% end %>

<div id="modal_place_bid" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <%= form_tag(Bid.new, id: "general_form_bid", remote: true) do %>
        <div class="modal-header">
          <h4 class="modal-title">Confirma tu oferta</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        <div class="modal-body">
          <p>Por favor confirma la cantidad que deseas ofertar para:</p>
          <h3 class="text-center"><span class="span_product_name"></span></h3>
          <div class="div_bid_hidden_fields"></div>
          <div class="div_bid_amount_field w-50 mx-auto"></div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
          <%= submit_tag "Ofertar", class: "btn btn-primary bid_amount" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<script type="text/javascript">
  function products_refresh() {
    $.get( "bids/render_bids_row?product_ids_order=<%= @products.map(&:id).join('+') %>", function( data ) {
      $("#bids_products_row").html(data);
    });
    setInterval(function(){
      products_refresh()
    }, 60000);
  }
</script>

app/views/bids/render_bids_row.html.erb
<%= render "bids/bids_products" %>