config/routes.rb
Rails.application.routes.draw do
  get 'statics/coming'
  devise_for :users
  resources :users, only: :index
  resources :products
  resources :bids, only: [:index, :create]
  get "bids/render_bids_row"

  # root "statics#coming"
  root "bids#index"
end

app/views/layouts/_timer.html.erb
<div class="row text-center">
  <div class="col-12 col-md-12 col-lg-6 col-xl-6 my-4 mx-auto" id="finish">

    <div class="row">

      <div class="col-12 col-sm-3 col-md-3">
        <div class="row">

          <div class="col-12">
            <div class="row" >
              <div class="col-12" id="cronometroDay" style="font-size:3rem"></div>
            </div>
            <div class="row">
              <div class="col-12">Días</div>
            </div>
          </div>
        </div>
      </div>

      <div class="col-12 col-sm-9 col-md-9">
        <div class="row">

          <div class="col-3">
            <div class="row">
              <div class="col-12"  id="cronometroHh" style="font-size:3rem"></div>
              <div class="col-12 text-center">Hrs</div>
            </div>
          </div>

          <div class="col-1" style="font-size:3rem">:</div>

          <div class="col-3">
            <div class="row" >
              <div class="col-12" id="cronometroMm" style="font-size:3rem"></div>
              <div class="col-12 text-center">Min</div>
            </div>
          </div>

          <div class="col-1" style="font-size:3rem">:</div>
          
          <div class="col-3">
            <div class="row">
              <div class="col-12" id="cronometroSs" style="font-size:3rem"></div>
              <dic class="col-12 text-center">Seg</dic>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  var contador
  var stopWatch

  function secondsToString(contador){
    d = Math.floor(contador/86400)
    day = (d<10)? '0'+ d:d;
    hh = Math.floor((contador / 3600)%24);
    hour = (hh < 10)? '0' + hh : hh ;
    mm = Math.floor((contador / 60) % 60);
    minute = (mm < 10)? '0' + mm : mm;
    ss = contador % 60;
    second = (ss < 10)? '0' + ss : ss;
    return day +  hour + minute + second;
  };
   
  function updateDisplay(){
    endTimer = new Date(2021,10,23,10,17)  // (año_num,mes_num(los meses son del 0 al 10),dia_num[hora_num, min_num, segundo_num])
    startTimer = new Date()
    contador = Math.floor((endTimer.getTime()-startTimer.getTime())/1000)
    clearInterval(stopWatch)
    stopWatch = setInterval(updateDisplay,1000)
    if (contador > 0) {
      contador--;
    }else{
      clearInterval(stopWatch)
      day = "00"
      hour = "00" 
      minute = "00" 
      second = "00"
      document.getElementById("finish").innerHTML = "¡¡La subasta ha terminado!!" 
      return contador = 0
    };
    secondsToString(contador);
    document.getElementById("cronometroDay").innerHTML = day
    document.getElementById("cronometroHh" ).innerHTML = hour
    document.getElementById("cronometroMm" ).innerHTML = minute 
    document.getElementById("cronometroSs" ).innerHTML =  second
  }; 
    
    updateDisplay();

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Buen Fin Solidario</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-11 mx-auto">
          <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a><%= link_to "Subasta Solidaria", root_path, :class => "navbar-brand"%></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="form-inline nav-item">
                  <% if user_signed_in?%>
                    <% if current_user.admin%>
                      <a class="nav-link"><%= link_to "Subasta", bids_path, :class => "nav-link"%></a>
                      <a class="nav-link"><%= link_to "Productos", products_path, :class => "nav-link"%></a>
                      <a class="nav-link"><%= link_to "Usuarios", users_path, :class => "nav-link"%></a>
                    <% end %>
                  <% end%>
                </li>
              </ul>
              <ul>
                <li class="form-inline my-2 my-lg-0 nav-item flex-grow-2 dropdown active">
                  <a href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <% if user_signed_in? %>
                      <%= current_user.email %>
                    <% else %>
                      <span class="fas fa-user" style="font-size: 20px;"></span>
                    <% end %>
                  </a>
                  <% if user_signed_in? %>
                    <div class="dropdown-menu m-0 " aria-labelledby="navbarDropdown">
                      <%= label_tag current_user.email, nil, class: "px-4 pt-2 text-muted" %>
                      <%= link_to "Perfil", edit_user_registration_path, :class => "nav-link" %>
                      <%= link_to "Salir", destroy_user_session_path, method: :delete, :class => "nav-link" %>
                    </div>
                  <% else %>
                    <div class="row row-cols-1 row-cols-md-2">
                      <div class="col">
                        <%= link_to "Registrarse", new_user_registration_path, class: "navbar-link btn btn-outline-success btn-md m-1" %>
                      </div>
                      <div class="col">
                        <%= link_to "Iniciar Sesión", new_user_session_path, class: "navbar-link btn btn-outline-primary btn-md m-1 text-nowrap" %>
                      </div>
                    </div>
                  <% end %>
                </li>
              </ul>
            </div>
          </nav>
          <div class="col-md text-center"><td><%= image_tag "ARRIBA.png", class: "m-2", style: "max-width: 100%;" %></td></div>
          <% if flash[:notice].present? %>
            <div class="alert alert-success mb-2" role="alert" id="alert1">
              <%= notice %>
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
          <% elsif flash[:alert].present? %>
            <div class="alert alert-danger mb-2" role="alert" id="alert2">
              <%= alert %>
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
          <% end %>
          
          <%= render "layouts/timer" %>
          
          <%= yield  %>
          <div class="container-fluid mx-auto w-55 p-3 text-center bg-light">
            <div class="row">
              <ul class="mx-auto w-55 p-3 text-center">
                  Comité Organizador del Buen Fin Solidario
              </ul>
            </div>
            <div class="row mx-auto text-center">
              <div class="col-md text-center"><td><%= image_tag "ABAJO.png", style: "max-width: 100%;" %></td></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>